### ISSUE TITLE
application.h

### ISSUE THREAD

**Issue by DDetlefsen** [Seeed-Studio/Grove_Starter_Kit_for_Photon_Demos#1]
Hello,
I see that several of the example projects #include "application.h".  Should this .h file be included in the example and project folders? Copying the code into the Particle Build does not seem to work without this file.  Am I misunderstanding something?

Thanks for the help.

**Comment by coomsie** [comment]
that's photon's equivalent of "ardurino.h" , so yes basic functions need this ...
